### ISSUE TITLE
Wrong title bar background height

### ISSUE THREAD

**Issue by EFanZh** [pixelocdguy/windows-classic#1]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/2160692/216301944-68ccbacb-677e-4b21-9e99-58dab4490b39.png">

The background does not match the text. Maybe it have something to do with the monitor DPI? I have a 4K monitor.

**Comment by coconitro** [comment]
Running into this as well. 4k monitor with global scale at 125%. Even at global scale 100% the issue persists if you change the button size.

**Comment by pixelocdguy** [comment]
Sorry I completely missed this! The theme is currently only supports 100% DPI. This was by design, as back when these versions of Windows were used almost no one used scaling and it doesn't look the same. If you did use scaling it really changed the overall look of Windows and frankly, didn't look that good. It may be added in a future update due to so many people having high DPI monitors now. Otherwise, feel free to submit a patch or asset update.
